# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Videona' do
pod 'Google/SignIn'
pod 'Google/Analytics'
pod 'Alamofire', '~> 3.3'
pod 'Mixpanel'
pod 'PermissionScope'
end

target 'VideonaTests' do

end

target 'VideonaUITests' do

end

